// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vthdeujvxtqjpzaxvceu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aGRldWp2eHRxanB6YXh2Y2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjIzNTEsImV4cCI6MjA3Mzg5ODM1MX0.4aXOfC5HEXd89_fyoSpmm04Jh09idWKPj5iRRLeAJNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});